services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: world_app_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - app-storage:/var/www/html/storage
      - app-bootstrap:/var/www/html/bootstrap/cache
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
      - "DB_DATABASE=world_db"
      - "DB_USERNAME=world_user"
      - "DB_PASSWORD=world_password"
    user: "1000:1000"
    depends_on:
      - postgres
    networks:
      - world_network

  nginx:
    image: nginx:alpine
    container_name: world_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - app-public-build:/var/www/html/public/build:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - world_network

  postgres:
    image: postgres:16-alpine
    container_name: world_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=world_db"
      - "POSTGRES_USER=world_user"
      - "POSTGRES_PASSWORD=world_password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - world_network

volumes:
  postgres_data:
  app-storage:
  app-bootstrap:
  app-public-build:

networks:
  world_network:
    driver: bridge
